services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command:
      --config /tmp/examples/config.yaml
    ports:
      - '9999:9999'
    volumes:
    - type: bind
      source: ./backend
      target: /tmp
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: torii
    ports:
      - 5432:5432
