services:
  frontend:
    restart: always
    build: 
      context: frontend
      dockerfile: Dockerfile.dev
    command: npx vite --host 0.0.0.0 --port 80
    ports: 
      - 8080:80
    volumes:
      - $PWD/frontend:/app
      - torii-frontend-node-modules:/app/node_modules
    depends_on:
      backend:
        condition: service_started

  backend:
    build: 
      context: backend
      dockerfile: Dockerfile.dev
    command: cargo run --config /app/exemples/config.yaml
    ports:
      - '9999:9999'
    volumes:
    - type: bind
      source: ./backend
      target: /tmp
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999" ]
    environment:
      - DB_CONNECTION_URL=postgresql://postgres:postgres@postgres:5432/torii
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: torii
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  torii-frontend-node-modules:
  