name: Build docker image next

on:
  push:
    branches:
      - feature/**

jobs:
  build-portal-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%Hh%M')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:backend"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/qovery/portal:next,ghcr.io/qovery/portal:next-${{ steps.date.outputs.date }}
